# This file compiled from .travis.yml.in

sudo: true

language: python

python:
  - "3.5"

install:
  # Install Python dependencies
  - python -m pip install --upgrade pip==8.1.1
  - python -m pip install -r requirements3.txt

script:
  - nosetests
