version: "2"
services:
  serv:
    build: ../../
    ports:
      - "8888:8888"
    container_name: serv
    #networks: 
    #  - app_network
    volumes:
      - ../shared_files:/shared
      - .:/code
    #entrypoint:
    #  - python
    #  - /code/master_node.py

  emu1:
    build: ../../
    container_name: emu1
    #ports:
    #  - "8888"
    #networks:
    #  - app_network
    volumes:
      - ./data/emu1:/screenshots
      - ../shared_files:/shared
      - .:/code
    #entrypoint:
    #  - python
    #  - /code/docker_emu_node.py

  # test1:
  #   build: ../
  #   container_name: test
  #   #networks:
  #   #  - app_network
  #   volumes:
  #     - .:/code

  #emu2:

   # build: C:\Users\ansross\Documents\Research\Android_Accessability_Capture\docker-accessibility-capture
    #networks:
    #  - app_network
    #volumes:
     # - C:\Users\ansross\Documents\Research\Android_Accessability_Capture\docker-accessibility-capture\data\emu2
